import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import ClientStoreInitializer from "@/components/ClientStoreInitializer";
import { getAccounts } from "@/db/db.util";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accounts = await getAccounts();
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          inter.className
        )}
      >
        <main className=" min-h-screen min-w-screen bg-gradient-to-r from-blue-300 to-purple-300">
          <ClientStoreInitializer accounts={accounts} />
          <Header />
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
