export const transactionTypeOptions = [
  { text: "Investment to Cash", value: "INVESTMENT_TO_CASH" },
  { text: "Investment to Bank", value: "INVESTMENT_TO_BANK" },
  { text: "Investment to Asset", value: "INVESTMENT_TO_ASSET" },
  { text: "Loan to Bank", value: "LOAN_TO_BANK" },
  { text: "Loan to Cash", value: "LOAN_TO_CASH" },
  { text: "Loan to Asset", value: "LOAN_TO_ASSET" },
  { text: "Cash to Loan (repayment)", value: "CASH_TO_LOAN" },
  { text: "Bank to Loan (repayment)", value: "BANK_TO_LOAN" },
  { text: "Cash to Asset", value: "CASH_TO_ASSET" },
  { text: "Bank to Asset", value: "BANK_TO_ASSET" },
  { text: "Asset to Bank (Sell)", value: "ASSET_TO_BANK_SELL" },
  { text: "Asset to Cash (Sell)", value: "ASSET_TO_CASH_SELL" },
  { text: "Asset to Bank (Hire)", value: "ASSET_TO_BANK_HIRE" },
  { text: "Asset to Cash (Hire)", value: "ASSET_TO_CASH_HIRE" },
  { text: "Bank to Expense", value: "BANK_TO_EXPENSE" },
  { text: "Cash to Expense", value: "CASH_TO_EXPENSE" },
  { text: "Loan to Expense", value: "LOAN_TO_EXPENSE" },
  { text: "Bank to Cash", value: "BANK_TO_CASH" },
  { text: "Cash to Bank", value: "CASH_TO_BANK" },
  { text: "Client to Bank", value: "CLIENT_TO_BANK" },
  { text: "Client to Cash", value: "CLIENT_TO_CASH" },
];
